-- DevHub phase 2: authentication profiles, roles, and RLS policies.
-- Run this file in Supabase SQL Editor or through the Supabase CLI.

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  constraint roles_key_check check (key in ('admin', 'team_lead', 'member', 'viewer'))
);

insert into public.roles (key, name, description)
values
  ('admin', 'Admin', 'Full access to DevHub.'),
  ('team_lead', 'Team Lead', 'Can manage team operations and reports.'),
  ('member', 'Member', 'Can manage personal work and learning items.'),
  ('viewer', 'Viewer', 'Read-only access to dashboard and reports.')
on conflict (key) do update
set
  name = excluded.name,
  description = excluded.description;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  avatar_url text,
  role_id bigint not null references public.roles(id),
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_status_check check (status in ('active', 'disabled'))
);

create index if not exists users_role_id_idx on public.users(role_id);
create index if not exists users_email_idx on public.users(email);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at
before update on public.users
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_role_id bigint;
begin
  select id into default_role_id
  from public.roles
  where key = 'member';

  insert into public.users (id, email, full_name, role_id)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    default_role_id
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(public.users.full_name, excluded.full_name);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select r.key
  from public.users u
  join public.roles r on r.id = u.role_id
  where u.id = auth.uid()
  limit 1;
$$;

alter table public.roles enable row level security;
alter table public.users enable row level security;

drop policy if exists "roles are readable by authenticated users" on public.roles;
create policy "roles are readable by authenticated users"
on public.roles
for select
to authenticated
using (true);

drop policy if exists "users can read own profile or team profiles" on public.users;
create policy "users can read own profile or team profiles"
on public.users
for select
to authenticated
using (
  id = auth.uid()
  or public.current_user_role() in ('admin', 'team_lead')
);

drop policy if exists "admins can manage all users" on public.users;
create policy "admins can manage all users"
on public.users
for all
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

-- After creating the first auth user, promote it manually:
-- update public.users
-- set role_id = (select id from public.roles where key = 'admin')
-- where email = 'admin@company.com';
